name: cheapest_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.5.0
  flutter_bloc: ^6.1.3
  equatable: ^1.0.2
  shared_preferences: ^0.5.4
  rxdart: ^0.22.3
  easy_localization: ^1.3.1
  connectivity:
  url_launcher:
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.0.0
  smooth_page_indicator:
  line_icons:
  badges:
  flare_flutter:
  gesture_zoom_box: ^0.0.2
  package_info:
  intl:
  hive: ^1.4.4+1
  hive_flutter:
  get_it:
  tab_indicator_styler: ^1.0.0
  animations:
  email_validator: ^1.0.5
  share: ^0.6.5+4
  provider:
  sticky_headers: ^0.1.8+1
  rounded_loading_button:
  awesome_dialog: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator:
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter-Black.ttf
         - asset: assets/fonts/Inter-Bold.ttf
         - asset: assets/fonts/Inter-ExtraBold.ttf
         - asset: assets/fonts/Inter-ExtraLight.ttf
         - asset: assets/fonts/Inter-Light.ttf
         - asset: assets/fonts/Inter-Medium.ttf
         - asset: assets/fonts/Inter-Regular.ttf
         - asset: assets/fonts/Inter-SemiBold.ttf
         - asset: assets/fonts/Inter-Thin.ttf
         - asset: assets/fonts/Inter-VariableFont.ttf